name: CI Pipeline
description: This Continuous Integration pipeline is for an Ai summary App

on:
    push:
        branches:
            - main
    pull_request: 
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # checking out code from repo
            - name: Checkout Repository
              uses: actions/checkout@v4

            #install Node
            - name: Install and Setup Node js
              uses: actions/setup-node@v4
              with:
                  node_version: 22

            # install all dependencies
            - name: Install all Dependencies
              run: npm ci


    